postgresql 10 with postgis 2.4
camptocamp/docker-postgres pull request #8
Opened 2017-11-02 12:52 UTC by tcoupin

postgis 2.4 for older postgresql versions are builded again GEOS 3.4 but some functions like ST_VoronoiPolygons need GEOS >=3.5.0

2017-11-02 13:00 UTC, fredj commented
should be `10.0` (directory) instead of `10` (and also `FROM postgres:10.0` instead of `FROM postgres:10`)

2017-11-02 13:05 UTC, tcoupin commented
rename done

2017-11-02 15:05 UTC, fredj commented
@mcanevet, @mbornoz, @sbrunner any comment on this?

2017-11-02 15:05 UTC, fredj approved these changes

2017-11-02 16:01 UTC, mcanevet commented
@tcoupin @fredj isn't it possible to install both Postgis versions like we do with postgres 9.5 and 9.6?

2017-11-02 16:10 UTC, tcoupin commented
Time to move to travis-ci for build to use ARGS ?

2017-11-02 16:15 UTC, mcanevet commented
@tcoupin I can't see the point of having multiple images if we don't have to.
What would be the image name in that case?

2017-11-02 16:16 UTC, mcanevet requested changes
Please don't use the ARGS directive and install all PostGIS supported versions

2017-11-02 19:45 UTC, tcoupin commented
Having multiple version is useful for integration tests against multiple environments.
For names, just follow officials images tag rules:
- latest, 10, 10.0, 10-pgis2.4, 10.0-pgis2.4, pgis2.4
- 9, 9.6, 9-pgis2.4, 9.6-pgis2.4, 9-pgis2.3, 9.6-pgis2.3, 9-pgis2.2, 9.6-pgis2.2
...

2017-11-03 06:59 UTC, tcoupin commented
Don't install all posgis version in the same image, it's not container philosophy "keep it small"

2017-11-03 07:49 UTC, mcanevet commented
@tcoupin I don't agree to change only for 10.0, please provide a PR for adding PostgreSQL 10.0 support the same way we do for 9.5 and 9.6 (this one I'll merge ASAP) and another PR with a proposal for changing the way we do for all PostgreSQL versions (this one will need a little bit more discussion).

2017-11-04 15:32 UTC, tcoupin commented
Update done, I open the #9 for discussion

2017-11-05 07:20 UTC, mcanevet approved these changes

2017-11-05 07:21 UTC, merged

2017-11-05 07:22 UTC, mcanevet commented
@tcoupin thanks.
Build in progress on DockerHub